# Generated by Django 2.2.6 on 2019-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creation_date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name_text',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='annonymous', max_length=30),
            preserve_default=False,
        ),
    ]
