# Generated by Django 2.2.6 on 2019-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20191003_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_name',
            field=models.CharField(default='No name', max_length=30),
            preserve_default=False,
        ),
    ]
